name: Mark as Done

on:
  push:
    tags:
      - v*

jobs:
  mark-as-done:
    runs-on: ubuntu-latest
    if: false # Skip this for now, until auto-mate is made public
    steps:
      - name: Move closed issues and merged PRs to the "✅ Done" column
        uses: grafana/auto-mate@v1
        with:
          token: ${{ secrets.AUTO_MATE_TOKEN }}
          projectNo: 346
