name: Test Okta Logs Collector

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - ".gitignore"
      - ".gitattributes"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - ".gitignore"
      - ".gitattributes"

jobs:
  test:
    name: Test Okta Logs Collector
    runs-on: ubuntu-latest
    # Timeout after 5 minutes, to avoid hanging tests
    timeout-minutes: 5
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go 🧑‍💻
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Lint code with golangci-lint 🚨
        uses: golangci/golangci-lint-action@v4
        with:
          version: "v1.59"
          skip-pkg-cache: true
          install-mode: "goinstall"

      - name: Lint Dockerfile with hadolint 🚨
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Run Go tests 🔬
        run: go test -p 1 -cover -covermode atomic -coverprofile=profile.cov -v ./...

      - name: Report coverage to coveralls 📈
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
